// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBap3Of9HpGMBqlrjyUzeXrE3HIUlYr1uQ',
    appId: '1:1018385132041:web:ad27922b54af79fe9ce6d8',
    messagingSenderId: '1018385132041',
    projectId: 'expense-manager-c071e',
    authDomain: 'expense-manager-c071e.firebaseapp.com',
    databaseURL: 'https://expense-manager-c071e-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-c071e.firebasestorage.app',
    measurementId: 'G-2WER7BKGLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NJ0E4aLkzuR5mymMN5hunxmEs8nRZew',
    appId: '1:1018385132041:android:89166228007b81d69ce6d8',
    messagingSenderId: '1018385132041',
    projectId: 'expense-manager-c071e',
    databaseURL: 'https://expense-manager-c071e-default-rtdb.firebaseio.com',
    storageBucket: 'expense-manager-c071e.firebasestorage.app',
  );
}
